### PR TITLE
HVAC Setpoint Fixes

### PR DESCRIPTION
**Pull request by gervaso**
Integrating Dan Bemowski's patches to handle single setpoint thermostats in Vera UI.
See the following link for details: https://forum.mysensors.org/topic/5660/thermostat-bridge-hvac-node-issues/9

### CODE REVIEW

**Comment by henrikekblad** [comment]
Thanks!

**Comment by gervaso** [comment]
Thank you for the quick reply but there's still one issue left, i think: the "HVAC_SETPOINT" which has been "arbitrarily" assigned the id 54 is already used in "MyMessage.h", shall we ask for a new id to the core team?

**Comment by henrikekblad** [comment]
Hm.. Darn.. Hadn't fully read through the whole forum thread. The HVAC/Heater devices in vera have always been troublesome. So little documentation and many variants (or things have been changed through Vera versions if I understand it correctly).    

The HVAC devices already uses: 
V_STATUS, V_TEMP, V_HVAC_FLOW_STATE , V_HVAC_SPEED, V_HVAC_SETPOINT_COOL, V_HVAC_SETPOINT_HEAT, V_HVAC_FLOW_MODE

... and now another V_HVAC_SETPOINT. It wouldn't be possible to (re-)use V_LEVEL for incoming setpoint?

**Comment by gervaso** [comment]
Oh, I've created a new issue in the core library to have a new id assigned. I'm not seeing a particular issue in "recycling" V_LEVEL for this task except for the fact that maybe is not really intuitive.
I'm completely new on this sensors world, so I don't know if there are any implications with both cases (adding a new ID or using V_LEVEL).

**Comment by henrikekblad** [comment]
V_LEVEL is supposed to be a generic "level" that can be recycled between device types (to keep down the new number of new VARs). It was introduced rather late so I'm not sure it has been used in the Vera plugin at all to this date.

So I see no problem if you use reusing it for the HVAC as a HVAC setpoint.

**Comment by gervaso** [comment]
Ok, sounds good, I'll check and patch the code later this evening (GMT+1  timezone).

**Pull request merged**
