### PR TITLE
Bekkie adding ir support

### PR DESCRIPTION
**Pull request by Bekkie**
This change depends on V_IR_RECORD which is proposed in another pull request

It also relies on 3 images being present on your webserver
http://www.mysensors.org/icon/RemoteControl.png
http://www.mysensors.org/icon/RemoteControl_0.png
http://www.mysensors.org/icon/RemoteControl_100.png

I will post them in the forum

### CODE REVIEW

**Comment by henrikekblad** [comment]
Strange, there are conflicts. 
Did you create this pull request from a branch originating from development-branch?

**Comment by Bekkie** [comment]
As far as i can remember from the dev-branch. What are the conflict?

**Comment by Bekkie** [comment]
I see also strange changes in I_Arduino1.xml. let me check the code in the afternoon.

Altest this code snipped needs to be added
   <action>
  	   	<serviceId>urn:schemas-arduino-cc:serviceId:ArduinoIr1</serviceId>
	     	<name>RecordIrCode</name>
	     	<job>
			luup.log("Record IR code #" .. lul_settings.Index .. " with name: " .. lul_settings.CodeName)
  			if (p ~= nil) then p.recordIrCode(lul_device, lul_settings.Index, lul_settings.CodeName) end
			return 4,0
	     	</job>
     </action>

**Comment by henrikekblad** [comment]
The icons has been deployed on mysensors.org now.

**Comment by Bekkie** [comment]
Do you need help to resolve the merge conflict?

**Comment by henrikekblad** [comment]
Yes, would be great if you could resolve the conflict.

**Pull request closed without merging**
