### PR TITLE
Changes for better look-and-feel in UI7

### PR DESCRIPTION
**Pull request by olaeke2**
Changes to make the "bricks" in UI7 to work better, changes only made to main "bricks" not yet implemented on barometer, distance and the other.
No guarantee that it is totaly correct due to almost total lack of documentation for develop in UI7 so it is most "trial and error"

### CODE REVIEW

**Comment by henrikekblad** [comment]
Hehe.. trial and error sound familiar when it comes to Vera UI development. Looks good (even if I cannot actually verify it on my UI6).

The pull request was created on the master branch. If you could:
* check out latest from github.
* Switch to UI7-branch
* Merge your changes into your local UI7-branch.
* Push to github
* Redo pull request from your UI7 branch on github. 

Also, would be great if you could add your name to the CLA
https://www.clahub.com/agreements/mysensors/Vera

**Comment by olaeke2** [comment]
Hi

Stupid Q but how do I check out? As I said before so am I not used to this tool

Or can you just delete what I did in master and then I can redo, and try to select correct branch

 

I cant edit CLA i allways got this error when I click I agree

We're sorry, but something went wrong.

 

/Ola

 

Från: Henrik Ekblad [mailto:notifications@github.com] 
Skickat: den 29 januari 2015 23:45
Till: mysensors/Vera
Kopia: olaeke2
Ämne: Re: [Vera] Changes for better look-and-feel in UI7 (#10)

 

Hehe.. trial and error sound familiar when it comes to Vera UI development. Looks good (even if I cannot actually verify it on my UI6).

The pull request was created on the master branch. If you could:

*	check out latest from github.
*	Switch to UI7-branch
*	Merge your changes into your local UI7-branch.
*	Push to github
*	Redo pull request from your UI7 branch on github. 

Also, would be great if you could add your name to the CLA
https://www.clahub.com/agreements/mysensors/Vera

**Comment by henrikekblad** [comment]
It takes a while getting used to git. But once you learn it you'll most probably find it awesome. 

Checkout = git pull (this will fetch updates from upstream which is github in your case). The pull will contain the new UI7 branch.  
So the easiest is probably to copy the files you have updated to some temporary folder. Switch to ui7 and copy them back. Like this

> git pull
> git checkout ui7 - switches to ui7 branch 
(copy the saved files)
> git commit -m "commit message"  - commit files (locally)
> git push - pushed the current branch to upstream.

-----
git checkout master - switches back to master

**Comment by henrikekblad** [comment]
Ok, redid the PR myself. Thanks for the UI7 update.

**Comment by olaeke2** [comment]
Ok, sorry but I’m on business travel so I’m away from my home computer where I have the fun stuff (=MySensors thing) that’s why I haven’t had time to fix it. 

So then I can I drop it now ?

 

Regards

Ola

 

Från: Henrik Ekblad [mailto:notifications@github.com] 
Skickat: den 3 februari 2015 19:55
Till: mysensors/Vera
Kopia: olaeke2
Ämne: Re: [Vera] Changes for better look-and-feel in UI7 (#10)

 

Ok, redid the PR myself. Thanks for the UI7 update.

**Comment by henrikekblad** [comment]
Yep, merged. Enjoy the trip ;)

**Pull request closed without merging**
